### ISSUE TITLE
UTF-8 problems

### ISSUE THREAD

**Issue by jaksmid** [mit-nlp/MITIE#51] opened 2016-05-23 09:16 UTC
Hi, 

First of all thank let me thank you for this great tool.
We are using MITIE via python 2.7. To my best knowledge we have to convert our strings from unicode to plain bytes before passing them to MITIE. 
When using tokenize_with_offset this can lead to some offset detected in the middle of some unicode character spanning over multiple bytes which results in "UnicodeDecodeError: 'utf8' codec can't decode bytes in position 4-5: unexpected end of data" after attempt for decode.

Any ideas?

Many thanks,
Jakub

**Comment by davisking** [comment] 2016-05-23 10:44
I'm not sure what to suggest other than to be careful about being
consistent in your use of utf8.  With utf8 there shouldn't be any problems.

**Comment by jaksmid** [comment] 2016-05-23 11:22
But python wrapper around mitie does not support UTF-8 (hence the conversion). Or am I mistaken?

**Comment by jaksmid** [comment] 2016-05-23 11:31
At least if I call mitie.tokenize_with_offsets(somenonascii_unicodechar) I get the error.
Thats why we convert to python 2.7 string (which is equal to bytes).
Mitie model than happily detects entites that are in the middle of some unicode string as it does not know about the unicode. And the backwards conversion is no longer possible.
From your comment it seems it is the issue in the python API to mitie.
But we have coding consistent, it is because of mitie we had to create this inconsistency.

**Comment by lopuhin** [comment] 2016-05-23 11:35
@jaksmid do you have any example of the input that cases errors for tokenize_with_offsets? I tried some unicode inputs and could not trigger the error.

**Comment by jaksmid** [comment] 2016-05-23 11:48
#!/usr/bin/env python
# -*- coding: utf-8 -*-
import mitie
tokens_with_offset = mitie.tokenize_with_offsets(u'Bart’s home')

Results in Traceback (most recent call last):
  File "/Users/smidj/PycharmProjects/literature-search-pipeline/main.py", line 8, in <module>
    tokens_with_offset = mitie.tokenize_with_offsets(u'Bart’s home')
  File "/Users/smidj/.virtualenvs/ls/lib/python2.7/site-packages/mitie/mitie.py", line 161, in tokenize_with_offsets
    tok = mitie_tokenize(str, ctypes.byref(token_offsets))
ctypes.ArgumentError: argument 1: <type 'exceptions.UnicodeEncodeError'>: 'ascii' codec can't encode character u'\u2019' in position 4: ordinal not in range(128)

**Comment by lopuhin** [comment] 2016-05-23 11:50
@jaksmid sorry I was not clear - I meant the error you get when encoding into utf-8

**Comment by jaksmid** [comment] 2016-05-23 12:02
Oh, I see.
Well, you can get the error like this:
u"Bart’s home".encode('utf-8')[0:6].decode('utf-8')
Something similar is obtainable for the beginning of the unicode.

As we have to convert to bytes before passing it to the mitie api, NER model can detect entities that, after looking their start and end positions using MITIE tokenizer result in invalid start and end positions from the point of view of the utf-8 encoding. We get the error after converting back to utf-8 but only the substring given by the start and end positions. I hope this description is clear enough.

Thanks,
Jakub

**Comment by lopuhin** [comment] 2016-05-23 12:11
> As we have to convert to bytes before passing it to the mitie api, NER model can detect entities that, after looking their start and end positions using MITIE tokenizer result in invalid start and end positions from the point of view of the utf-8 encoding. We get the error after converting back to utf-8 but only the substring given by the start and end positions. I hope this description is clear enough.

Yes, the description is clear - but I did not manage to get such invalid decodings myself. Can you provide such an example? More precisely, this is way I tried:
```
>>> [w.decode('utf-8') for w, _ in mitie.tokenize_with_offsets(u'альт или баян?'.encode('utf-8'))]
['альт', 'или', 'баян', '?']
```
Or, using indices:
```
>>> text = u'альт или баян?'
>>> utf8_text = text.encode('utf-8')
>>> result = mitie.tokenize_with_offsets(utf8_text)
>>> utf8_text[result[0][1]:result[1][1]].decode('utf-8')
'альт '
>>> utf8_text[result[1][1]:result[2][1]].decode('utf-8')
'или '
```

The indices are offsets into the utf-8 encoded string, as this is what MITIE gets.

**Comment by jaksmid** [comment] 2016-05-23 12:48
text = u"Hemoglobin Bart’s is a γ tetramer with a very high oxygen affinity, thus oxygen delivery to the tissues is poor."
import mitie
encoded_text=text.encode('utf-8')
result =mitie.tokenize_with_offsets(encoded_text)
result[2][0] == encoded_text[15:19]

The issue may be somewhat different. I am using the length of the string in token to detect the end of the token in text. However, in the above case I would expect the last line to be true as the token detected is the weird symbol plus s and encoded text correspond to that. Would you know why the comparison result in false?

**Comment by lopuhin** [comment] 2016-05-23 13:00
Looks like MITIE converts ``’`` into ``'`` during tokenize_with_offsets - not sure if this is expected (I'm not a MITIE developer, just use the Python API too). Perhaps this is some normalization step.
This seems to be a different issue though, right.

**Comment by davisking** [comment] 2016-05-23 13:05
Yes, the tokenizer does a little bit of normalization.  So that is the
expected behavior.

**Comment by jaksmid** [comment] 2016-05-23 14:04
But what if you want to detect the substring of the input text defined by the token? Only the beginning and normalised string is returned. For this you would also need the end of the token (beginning of the next token can be far far away and you cant guarantee that the length of the normalised token is the same as it would be without a normalization.

**Comment by davisking** [comment] 2016-05-23 14:14
If the beginning of the next token doesn't work for what you are trying to
do then you can write your own tokenizer and use that with MITIE.  There
isn't any reason you have to use the tokenizer that happens to come with
MITIE.

**Comment by jaksmid** [comment] 2016-05-23 14:57
Why would I want to write another tokenizer? I just want to save the positions in the original text and I am completely happy with the tokenizer as is.

I would expect that this normalization would be at least documented somewhere.
Better way would be IMHO to do the normalization internally as tokenization is part of the public API.  One would expect that the tokens are substrings of the original text. This normalization is more of a side effect.

**Comment by palicand** [comment] 2016-05-24 09:46
I agree with @jaksmid in that it does seem to be quite weird. Doing these normalisations internally does make sense, but IMO users would expect the output tokens to be denormalised, i. e. really a substring of the input. Or at least output both the normalised and original token.

**Comment by davisking** [comment] 2016-05-24 10:46
The MITIE tokenizer isn't going to be all things to all people.  I almost
didn't include a tokenizer with MITIE because I know many people who do
tokenization many different ways.  But a default one needs to be there so
the examples can run.  This is the default one, it isn't going to be the
one final tokenizer you can use for all tasks.  It is the tokenizer that
makes MITIE perform reasonably well on the examples and with a few
languages and tasks.  For some tasks you will have to create your own
tokenizer.  For example, maybe there is something inherent in the NLP
problem you are trying to solve that requires different notions of "words"
or you are doing some additional non-NLP task like making some kind of GUI
which needs some particular tokenization.  In those cases, make your own
tokenizer because MITIE isn't going to be a tokenizer library.  It's an NLP
library.

As for this normalization.  It's in MITIE because some users complained
about the tokenizer not doing it.  Adding it also slightly improves NER
performance on English and it's a minor change so it went into MITIE.
There are other users who would like even more normalization.  Some want
less. Tokenization is easy, if you want it done differently then do it some
other way.  You can still use MITIE with tokens from some other tokenizer.

**Comment by jaksmid** [comment] 2016-06-07 10:30
@lopuhin 
I got the original error we were discussing previously by running the following:
```
text = 'Department ‘‘B’’ of Charles Nicolle Hospital (Tunisia).'
tokens = mitie.tokenize_with_offsets(text)
for index, (token, offeset) in enumerate(tokens):
    begin = offeset
    if index+1 == len(tokens):
        end = len(text)
    else:
        end = tokens[index+1][1]
    substring = text[begin:end]
    unicode = substring.decode('utf-8')
```
This results in UnicodeDecodeError: 'utf8' codec can't decode byte 0xe2 in position 0: unexpected end of data. In this case, the tokenizer indeed detects a token end in the middle of the unicode character encoded by multiple bytes.

**Comment by lopuhin** [comment] 2016-06-07 10:44
@jaksmid I see, thanks. For this string the output is
```[(b'Department', 0), (b'\xe2\x80\x98\xe2\x80\x98B', 11), (b"'", 18), (b"'", 19), (b'of', 25), (b'Charles', 28), (b'Nicolle', 36), (b'Hospital', 44), (b'(', 53), (b'Tunisia', 54), (b')', 61), (b'.', 62)]```
and expected output would be (19 -> 22):
```[(b'Department', 0), (b'\xe2\x80\x98\xe2\x80\x98B', 11), (b"'", 18), (b"'", 22), (b'of', 25), (b'Charles', 28), (b'Nicolle', 36), (b'Hospital', 44), (b'(', 53), (b'Tunisia', 54), (b')', 61), (b'.', 62)]```

So looks like here one index is indeed wrong.

**Comment by davisking** [comment] 2016-06-08 00:11
Ah, yes, this is a bug in the MITIE tokenizer :)   I just pushed the fix to github, so it should give the correct byte offsets now.  Sorry for being such a nazi about this :)

**Closed by davisking** 2016-06-08 00:11 UTC
